[versions]
clikt = "5.1.0"
kmp-process = "0.5.0"
kotlin = "2.4.20"
okio = "3.18.2"

[libraries]
clikt-core = { module = "com.github.ajalt.clikt:clikt-core", version.ref = "clikt" }
kmp-process = { module = "io.matthewnelson.kmp-process:process", version.ref = "kmp-process" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
