name: Specs

on:
  pull_request:

  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "specs-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  install-kotlinstall:
    name: should install kotlinstall with the installer script
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: zulu
          java-version: "21"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Run the installer script
        run: cat install-kotlinstall.main.kts | kotlinr -howtorun .main.kts /dev/stdin --git "file://$GITHUB_WORKSPACE"

      - name: Run kotlinstall
        run: ~/.kotlinstall/bin/kotlinstall list

  install-program:
    name: should install a program written in Kotlin
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: zulu
          java-version: "21"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build kotlinstall
        run: ./gradlew linkReleaseExecutableMacosArm64

      - name: Install kotlinstall itself as the program written in Kotlin
        run: build/bin/macosArm64/releaseExecutable/kotlinstall.kexe install "file://$GITHUB_WORKSPACE"

      - name: Run the installed program
        run: ~/.kotlinstall/bin/kotlinstall list
